// docs/examples/events-parent/events-parent.vue
<script setup lang="ts">
import { ref } from "vue";
import { useDragAndDrop } from "@formkit/drag-and-drop/vue";

const dragStatus = ref("Not dragging");
const valuesChanged = ref("Not sorting");
const [parent, flavors] = useDragAndDrop(
  ["🍦 vanilla", "🍫 chocolate", "🍓 strawberry"],
  {
    onDragstart: () => {
      dragStatus.value = "Dragging";
    },
    onDragend: () => {
      dragStatus.value = "Not dragging";
      valuesChanged.value = "Not sorting";
    },
    onSort: (event) => {
      valuesChanged.value = `${event.previousValues} -> ${event.values}`;
    },
  }
);
</script>

<template>
  <div class="border-4 p-4 border-indigo-300 dark:bg-slate-800 antialiased">
    <div class="font-oldschool mb-4 text-lg md:text-xl lg:text-2xl">
      <span class="antialiased">=== Rank your favorite flavors ===</span>
      <div>Drag status: {{ dragStatus }}</div>
      <div>Values changed: {{ valuesChanged }}</div>
    </div>
    <div
      ref="parent"
      class="border-2 border-indigo-300 font-oldschool text-lg md:text-xl lg:text-2xl antialiased"
    >
      <div
        v-for="flavor in flavors"
        :key="flavor"
        class="border-2 border-indigo-300 p-2"
      >
        {{ flavor }}
      </div>
    </div>
  </div>
</template>

// docs/examples/events-parent/events-parent.tsx
import React from "react";
import { useState } from "react";
import { useDragAndDrop } from "@formkit/drag-and-drop/react";

export function App() {
  const [dragStatus, setDragStatus] = useState("Not dragging");
  const [valuesChanged, setValuesChanged] = useState("Not sorting");

  const [parent, items] = useDragAndDrop<HTMLUListElement, string>(
    ["🍦 vanilla", "🍫 chocolate", "🍓 strawberry"],
    {
      onDragstart: () => {
        setDragStatus("Dragging");
      },
      onDragend: () => {
        setDragStatus("Not dragging");
        setValuesChanged("Not sorting");
      },
      onSort: (event) => {
        setValuesChanged(`${event.previousValues} -> ${event.values}`);
      },
    }
  );

  return (
    <div>
      <strong>Rank your favorite flavors</strong>
      <br />
      <span>{dragStatus}</span>
      <span>{valuesChanged}</span>
      <br />
      <ul ref={parent}>
        {items.map((item) => {
          return <li key={item}>{item}</li>;
        })}
      </ul>
    </div>
  );
}
