// dev/react/App.tsx
import React from "react";

import { useState, useEffect } from "react";

import { dragAndDrop } from "../../src/react/index";

import reactLogo from "/reactjs-icon.svg";

function App() {
  const playingCardAssets = [
    "/cards/10_of_clubs.png",
    "/cards/jack_of_hearts.png",
    "/cards/queen_of_spades.png",
    "/cards/king_of_diamonds.png",
    "/cards/ace_of_clubs.png",
  ];

  const [values, updateValues] = useState(playingCardAssets);

  const playingCards = values.map((card: string) => (
    <li className="item" key={card}>
      <img src={card} />
    </li>
  ));

  useEffect(() => {
    const el = document.getElementById("playing_cards_react");

    if (!(el instanceof HTMLElement)) return;

    dragAndDrop({
      parent: el,
      values: [values, updateValues],
    });
  });

  return (
    <>
      <div>
        <div className="logo">
          <img src={reactLogo} alt="React Logo" />
        </div>
        <div className="content">
          <h3>Test 1: Init Parent</h3>
          <h4>
            Init parent by passing in the parent elmeent directly to
            `dragAndDrop` function.
          </h4>
          <ul id="playing_cards_react">{playingCards}</ul>
        </div>
      </div>
    </>
  );
}

export default App;

// dev/vue/App.vue
<script setup lang="ts">
import vueLogo from "/vuejs-icon.svg";

import { ref, onMounted } from "vue";

import { dragAndDrop } from "../../src/vue/index";

//dragAndDrop();
const playingCards = ref([
  "/cards/10_of_clubs.png",
  "/cards/jack_of_hearts.png",
  "/cards/queen_of_spades.png",
  "/cards/king_of_diamonds.png",
  "/cards/ace_of_clubs.png",
]);

onMounted(() => {
  const el = document.getElementById("playing_cards_vue");

  if (!(el instanceof HTMLElement)) return;

  dragAndDrop({
    parent: el,
    values: playingCards,
  });
});
</script>

<template>
  <div>
    <div class="logo">
      <img :src="vueLogo" className="logo" alt="Vite logo" />
    </div>
    <div class="content">
      <h3>Test 1: Init Parent</h3>
      <h4>
        Init parent by passing in the parent element directly to `dragAndDrop`
        function.
      </h4>
      <ul id="playing_cards_vue">
        <li v-for="card in playingCards" :key="card" class="item">
          <img :src="`${card}`" />
        </li>
      </ul>
    </div>
  </div>
</template>
