// docs/examples/animations/animations.tsx
import React from "react";
import { animations } from "@formkit/drag-and-drop";
import { useDragAndDrop } from "@formkit/drag-and-drop/react";

export function myComponent() {
  const [parent, tapes] = useDragAndDrop<HTMLUListElement, string>(
    [
      "ACDC LIVE",
      "Metallica",
      "Guns N' Roses",
      "Def Leppard",
      "Bon Jovi",
      "Van Halen",
    ],
    { plugins: [animations()] }
  );
  return (
    <ul ref={parent}>
      {tapes.map((tape) => (
        <li className="cassette" data-label={tape} key={tape}>
          {tape}
        </li>
      ))}
    </ul>
  );
}

// docs/examples/animations/animations.vue
<script setup lang="ts">
import { animations } from "@formkit/drag-and-drop";
import { useDragAndDrop } from "@formkit/drag-and-drop/vue";
const [parent, tapes] = useDragAndDrop(
  [
    "ACDC LIVE",
    "Metallica",
    "Guns N' Roses",
    "Def Leppard",
    "Bon Jovi",
    "Van Halen",
  ],
  { plugins: [animations()] }
);
</script>

<template>
  <ul ref="parent">
    <li v-for="tape in tapes" :key="tape" class="cassette">
      {{ tape }}
    </li>
  </ul>
</template>
