// docs/examples/update-config/update-config.vue
<script setup lang="ts">
import { useDragAndDrop } from "@formkit/drag-and-drop/vue";
import { ref } from "vue";

const disabled = ref(false);

const [parentRef, values, updateConfig] = useDragAndDrop([
  "Depeche Mode",
  "Duran Duran",
  "Pet",
  "Kraftwerk",
  "Tears for Fears",
  "Spandau Ballet",
]);

function toggleDisabled() {
  disabled.value = !disabled.value;

  updateConfig({ disabled: disabled.value });
}
</script>

<template>
  <ul ref="parentRef">
    <li v-for="tape in values" :key="tape" class="cassette">
      {{ tape }}
    </li>
  </ul>
  <button id="no-drag" @click="toggleDisabled">
    {{ disabled ? "Enable" : "Disable" }} drag and drop
  </button>
</template>

// docs/examples/update-config/update-config.tsx
import React from "react";
import { useState } from "react";
import { useDragAndDrop } from "@formkit/drag-and-drop/react";

export function myComponent() {
  const [parent, values, _setValues, updateConfig] = useDragAndDrop<
    HTMLUListElement,
    string
  >([
    "Depeche Mode",
    "Duran Duran",
    "Pet Shop Boys",
    "Kraftwerk",
    "Tears for Fears",
    "Spandau Ballet",
  ]);

  const [disabled, setDisabled] = useState(false);

  const toggleDisabled = () => {
    setDisabled(!disabled);

    updateConfig({ disabled: !disabled });
  };
  return (
    <div>
      <ul ref={parent}>
        {values.map((tape) => (
          <li className="cassette" data-label={tape} key={tape}>
            {tape}
          </li>
        ))}
      </ul>
      <button onClick={toggleDisabled}>
        {disabled ? "Enable" : "Disable"} drag and drop
      </button>
    </div>
  );
}
