// docs/examples/introduction/introduction.vue
<script setup lang="ts">
import { useDragAndDrop } from "@formkit/drag-and-drop/vue";
const [parent, flavors] = useDragAndDrop([
  "🍦 vanilla",
  "🍫 chocolate",
  "🍓 strawberry",
]);
</script>

<template>
  <strong>Rank your favorite flavors</strong>
  <div ref="parent">
    <div v-for="flavor in flavors" :key="flavor">
      {{ flavor }}
    </div>
  </div>
</template>

// docs/examples/introduction/introduction.tsx
import React from "react";
import { useDragAndDrop } from "@formkit/drag-and-drop/react";

export function myComponent() {
  const [parent, items] = useDragAndDrop<HTMLUListElement, string>([
    "🍦 vanilla",
    "🍫 chocolate",
    "🍓 strawberry",
  ]);
  return (
    <ul ref={parent}>
      {items.map((item) => (
        <li key={item}>{item}</li>
      ))}
    </ul>
  );
}
