// src/solid/types.ts
import type { Accessor, Signal } from "solid-js";
import type { ParentConfig } from "../types";

export type SolidElement<E extends HTMLElement> = E | Accessor<E>;

export interface SolidDragAndDropConfig<
  E extends Accessor<HTMLElement | null> | HTMLElement,
  ListItems extends unknown[]
> extends Partial<ParentConfig<ListItems[number]>> {
  parent: E;
  state: Signal<ListItems>;
}

// src/react/types.ts
import type { ParentConfig } from "../types";
import type { RefObject } from "react";

export type ReactElement<E extends HTMLElement> = E | RefObject<E>;

export interface ReactDragAndDropConfig<
  E extends RefObject<HTMLElement | null>,
  ListItems extends unknown[]
> extends Partial<ParentConfig> {
  parent: E;
  state: [ListItems, React.Dispatch<React.SetStateAction<ListItems>>];
}
