// docs/examples/drag-handles/drag-handles.tsx
import React from "react";
import { useDragAndDrop } from "@formkit/drag-and-drop/react";

export function myComponent() {
  const todoItems = ["Schedule perm", "Rewind VHS tapes", "Make change for the arcade", "Get disposable camera developed", "Learn C++", "Return Nintendo Power Glove"];
  const doneItems = ["Pickup new mix-tape from Beth", "Implement drag handles"];

  const [todoList, todos] = useDragAndDrop<HTMLUListElement, string>(
    todoItems,
    {
      group: "todoList",
      dragHandle: ".kanban-handle"
    }
  );
  const [doneList, dones] = useDragAndDrop<HTMLUListElement, string>(
    doneItems,
    {
      group: "todoList",
      dragHandle: ".kanban-handle"
    }
  );
  return (
    <div className="kanban-board">
      <ul ref={todoList} className="kanban-column">
        {todos.map((todo) => (
          <li className="kanban-item" key={todo}>
            <span className="kanban-handle"></span>
            {todo}
          </li>
        ))}
      </ul>
      <ul ref={doneList} className="kanban-column">
        {dones.map((done) => (
          <li className="kanban-item" key={done}>
            <span className="kanban-handle"></span>
            {done}
          </li>
        ))}
      </ul>
    </div>
  );
}

// docs/examples/drag-handles/drag-handles-solid.tsx
/** @jsxImportSource solid-js */
import { For } from "solid-js";
import { useDragAndDrop } from "@formkit/drag-and-drop/solid";

export function MyComponent() {
  const todoItems = [
    "Schedule perm",
    "Rewind VHS tapes",
    "Make change for the arcade",
    "Get disposable camera developed",
    "Learn C++",
    "Return Nintendo Power Glove",
  ];
  const doneItems = ["Pickup new mix-tape from Beth", "Implement drag handles"];

  const [todoList, todos] = useDragAndDrop<HTMLUListElement, string>(
    todoItems,
    {
      group: "todoList",
      dragHandle: ".kanban-handle",
    }
  );
  const [doneList, dones] = useDragAndDrop<HTMLUListElement, string>(
    doneItems,
    {
      group: "todoList",
      dragHandle: ".kanban-handle",
    }
  );

  return (
    <div class="kanban-board">
      <ul ref={todoList} class="kanban-column">
        <For each={todos()}>
          {(todo) => (
            <li class="kanban-item">
              <span class="kanban-handle"></span>
              {todo}
            </li>
          )}
        </For>
      </ul>
      <ul ref={doneList} class="kanban-column">
        <For each={dones()}>
          {(done) => (
            <li class="kanban-item">
              <span class="kanban-handle"></span>
              {done}
            </li>
          )}
        </For>
      </ul>
    </div>
  );
}
