// playground/vue/App.vue
<script setup lang="ts">
import Test1 from "./components/Test1.vue";
import Test2 from "./components/Test2.vue";
import vueLogo from "/vuejs-icon.svg";
</script>

<template>
  <div>
    <div class="logo">
      <img :src="vueLogo" className="logo" alt="Vite logo" />
    </div>
    <div class="content">
      <Test1
        id="vue_1"
        test-description="Init parent by passing in the parent element directly to `dragAndDrop` function."
      />
      <div class="divider"></div>
      <Test2
        id="vue_2"
        test-description="Init parent by passing in a Vue ref directly to `dragAndDrop` function."
      />
    </div>
  </div>
</template>

// playground/react/App.tsx
import React from "react";

import Test1 from "./components/Test1";

import Test2 from "./components/Test2";

import reactLogo from "/reactjs-icon.svg";

function App() {
  return (
    <>
      <div className="logo">
        <img src={reactLogo} alt="React Logo" />
      </div>
      <div className="content">
        <Test1
          id="react_1"
          testDescription="Init parent by passing in the parent element directly to `dragAndDrop` function."
        />
        <div className="divider"></div>
        <Test2
          id="react_2"
          testDescription="Init parent by passing in a React ref to `dragAndDrop` function."
        />
        <div className="divider"></div>
        <Test2
          id="react_3"
          testDescription="Init parent by using `useDragAndDrop` function."
        />
      </div>
    </>
  );
}

export default App;
